[project]
name = "escalonador-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "diskcache>=5.6.3",
    "fastapi[all]>=0.116.1",
    "requests>=2.32.4",
    "uvicorn[all]>=0.35.0",
]
